### ISSUE TITLE
Arquivos referenciados não disponíveis no repositório

### ISSUE THREAD

**Issue by thiagonf** [bacen/pix-dict-api#10]
Boa tarde, verifiquei que foi disponibilzado o **openapi.yaml** de como será a API do DICT que o BACEN irá prover. Achei bem legal a iniciativa, entretanto ao subir em um container do swagger-ui verifiquei que alguns arquivos não estão disponíveis para o import via $ref. O caminho inicial de alguns arquivos que faltam são:

- #/components/schemas
- #/components/responses

Segue abaixo o repositório com a configuração via docker-composer para subir o container com swagger-ui
https://github.com/lift-learning/pix-api

**Comment by luizlaydner** [comment]
No repositório, os arquivos estão separados para deixar mais organizado. Algumas ferramentas não são capazes de resolver referências externas da forma como está.
Sugiro usar a versão de release da spec: https://github.com/bacen/pix-dict-api/releases/download/v1.0.0/spec.yaml
