### ISSUE TITLE
[PROPOSTA] Adição de parâmetro para facilitar polling de participantes indiretos

### ISSUE THREAD

**Issue by luizlaydner** [bacen/pix-dict-api#12]
**Motivação**
Existem participantes diretos que oferecem acesso a um grande número de participantes indiretos. Algumas operações de polling da API do DICT, tais como listClaims e listInfractionReports, são feitas hoje para apenas um participante individual. A implicação disso é que esses participantes com muitos indiretos vinculados precisam fazer um grande número de chamadas à API, o que é ineficiente do ponto de vista de uso de recursos do sistema.

**Propostas**

_Alternativa 1_: Adicionar um parâmetro booleano opcional **includeIndirectParticipants** nas operações de listClaims e listInfractionReports, que quando **true** incluiria adicionalmente os claims/infractionReports de todos os indiretos vinculados ao participante direto que está solicitando.

_Alternativa 2_: Adicionar um parâmetro _array_ **indirectParticipant** que permitiria passar uma lista de participantes indiretos vinculados ao direto para os quais se deseja listar claims/infractionReports.

**Perguntas**:

- Tal funcionalidade é desejável para o seu participante ?
- Entre as alternativas apresentadas, alguma é preferível ?

**Comment by fCamargosRibeiro** [comment]
Sim, nós do BANCO COOPERATIVO SICREDI S.A temos hoje o cenário de 108 participantes, acho que seria mais fácil a alternativa 1, acho que nessa alternativa o impacto seria menor e a alteração seria mais rápida de fazer.

**Comment by anamorais83** [comment]
O Bancoob, instituição financeira do Sistema Sicoob, possui 397 participantes indiretos. Esta característica alinhada aos limitadores estabelecidos para a realização de chamadas à API dificulta o alcance do SLA estabelecido.

De fato a proposta apresentada é fundamental para otimizar a realização das operações citadas, tanto para a nossa infraestrutura quanto para a estrutura centralizada do Banco Central.

Para nós a Proposta 1 nos parece ser a mais adequada para o tratamento da questão.

**Comment by JeanFabichaki** [comment]
@luizlaydner Isso já está no ambiente de homologação? Nossas rotinas não estão mais funcionando devido a modificação do comportamento da API e testando agora esse parâmetro percebi que já está funcionando.

O comportamento da API foi alterada sem aviso?

**Comment by luizlaydner** [comment]
@JeanFabichaki conseguiria nos dizer qual foi o comportamento alterado ?
Está em homologação, mas a adição desse parâmetro opcional não deveria alterar comportamento.
Vamos investigar aqui.

**Comment by luizlaydner** [comment]
@fCamargosRibeiro  @anamorais83 : Foi publicada versão [1.1.0](https://github.com/bacen/pix-dict-api/releases/tag/v1.1.0) da API que adiciona o parâmetro `includeIndirectParticipants` na operação de listClaims
