### ISSUE TITLE
[Homolog][Dados] os dados do ambiente de homologação foram zerados?

### ISSUE THREAD

**Issue by erikacarvalho** [bacen/pix-dict-api#17]
olá!

ao tentar consultar, listar e agir sobre entries, claims e infraction reports em ambiente homolog estamos recebendo apenas respostas `404 Not Found` (ou listas fazias)

gostaria de saber: os dados em homolog foram zerados?

obrigada.

**Comment by evertongodoi** [comment]
@erikacarvalho conforme Comunicado aos participantes do Pix - 14/2020 enviado pelo Bacen na data de 03/12/2020, foi realizado expurgo do Banco de dados Dict, segue abaixo comunicado:

`Informamos também aos participantes que, em decorrência do início da nova etapa homologatória de participantes no Pix, todos os dados no ambiente de homologação serão expurgados. A partir de 7 de dezembro, o ambiente reabrirá para os participantes homologados, ou em processo de homologação, sem nenhum dado cadastrado anteriormente.`

**Comment by erikacarvalho** [comment]
obrigada @evertongodoi !
