### ISSUE TITLE
Reivindicação  e RequestId

### ISSUE THREAD

**Issue by morellibmv** [bacen/pix-dict-api#18]
Boa tarde,

percebemos que nossa instituição está fazendo muitas reconciliações ultimamente. Depois de uma investigação, identificamos que as reconciliações são causadas por chaves que passaram por um reivindicação - onde nossa instituição é o reivindicador - e que o dado inconsistente é o de Request ID da chave. O Request ID é o único campo utilizado no cálculo de CID que não acompanha o payload de Reivindicação. Acredito que seja o caso de nós como instituição reivindicadora, ao concluir a reivindicação, podermos informar um RequestID para que possamos, desde já calcular o CID corretamente sem a necessidade de realizar reconciliação para todas as chaves reivindicadas, pois reconciliação envolve custos.

**Comment by morellibmv** [comment]
Correção: na conclusão da reivindicação, é informado um RequestId. Este requestId é o utilizado no cálculo de CID?

**Comment by thiagostahlschmidt** [comment]
Está correto, esse é precisamente o motivo pelo qual o RequestId é retornado na conclusão de uma reivindicação.
Atualizaremos a API para deixar claro que esse campo é utilizado para calcular o CID do novo vínculo.
