### ISSUE TITLE
[Dúvida] Timeout de consulta de chave

### ISSUE THREAD

**Issue by wfreitaspq** [bacen/pix-dict-api#19]
Quanto tempo a chamada de consulta de chave no DICT deve entrar em timeout em caso de ausência de resposta?

**Comment by thiagostahlschmidt** [comment]
O timeout deve ser menor que 5s + o tempo médio do getEntry.
Se suas requisições de consulta de chave demoram em média 1s, o timeout deve ser menor que 6s.
