### ISSUE TITLE
Associação de chave de roteamento por IPs

### ISSUE THREAD

**Issue by mccraveiro** [bacen/pix-dict-api#2]
Lendo a documentação fiquei com a seguinte dúvida: o que aconteceria se duas instituições diferentes quiserem associar suas respectivas contas a uma mesma chave de roteamento (cpf, e-mail, etc)? Na apresentação do Pix foi falado que essa associação seria sempre de um para um para evitar que o comprador precisasse escolher a instituição de pagamento a partir de uma lista.

**Comment by luizlaydner** [comment]
A criação de um vínculo no DICT (associação de uma chave a uma conta trancional e pessoa) é, via de regra, feita a pedido do usuário titular da conta. Uma chave pode estar associada a uma conta. Uma conta pode estar associada a várias chaves.

Caso um PSP (provedor de serviços de pagamento) tente criar um vínculo no DICT com uma chave que já esteja vinculada a uma outra conta, da mesma pessoa, em um PSP diferente, o serviço retornará um erro:

[EntryKeyInCustodyOfDifferentParticipant](https://github.com/bacen/pix-dict-api/blob/cb1c06e8b6f99953e491825508f7a789fa7cdaf0/openapi/spec.yaml#L126)
Já existe vínculo para essa chave com o mesmo dono, mas ela encontra-se associada a outro participante. Indica-se que seja feita uma reivindicação de portabilidade.
