### ISSUE TITLE
[Dúvida] Lançamento da api 1.2

### ISSUE THREAD

**Issue by fabiomaciel** [bacen/pix-dict-api#20]

**Comment by wallace-brito** [comment]
Também tenho a mesma dúvida, quando a versão da API 1.2 do DICT estará disponível em homologação?

**Comment by fabiomaciel** [comment]
A documentação ja existe (https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API%20do%20DICT-v1.2.0.html),
porém o OpenAPI specification esta quebrado também.
