### ISSUE TITLE
[DICT] Impossibilidade de salvar um claim

### ISSUE THREAD

**Issue by iDanielScofield** [bacen/pix-dict-api#22]
**Descreva sua dúvida ou problema**

Ao realizar a _request_ para salvar uma Claim está sendo retornado "Bacen Message - Internal server error. Please contact support for details."

**Sistema ou Área**
DICT

**Identificador do Problema**
```
<type>https://dict.pi.rsfn.net.br/api/v1/error/InternalServerError</type>
<title>Internal Server Error</title>
<status>500</status>
<detail>Internal server error. Please contact support for details.</detail>
<correlationId>B202104261132190943965fab2d65a52</correlationId></problem>
```
Hora: em torno de 11:00h

Mensagens Enviadas / Recebidas

**Requisição:**

POST https://dict-h.pi.rsfn.net.br:16522/api/v1/claims
POST data:
```
{
   "claimerAccount":{
      "accountNumber":"462186",
      "accountType":"CACC",
      "branch":"5820",
      "participant":"99999012"
   },
   "key":"+5511471916107",
   "keyType":"PHONE",
   "type": "OWNERSHIP",
   "claimer":{
      "name":"Teste BV",
      "taxIdNumber":"98574764137",
      "type":"NATURAL_PERSON"
   }
}
```
[no cookies]

**Resposta:**
```
{
    "code": "3007",
    "origin": "BACEN",
    "messages": [
        "Bacen Message - Internal server error. Please contact support for details."
    ],
    "timestamp": "2021-04-26 02:32:19"
}
```
**URL de conexão**
https://dict-h.pi.rsfn.net.br:16522/api

**Comment by erikacarvalho** [comment]
estamos tendo o mesmo problema por aqui, tomando 500 ao tentar usar o endpoint "Criar Reivindicação" no ambiente de homolog.
correlation_id: `B20210427113335162b4ae95d845609b`

@bcb-thiago @luizlaydner conseguem dar uma posição? (se preferirem, eu posso abrir uma nova issue, mas como é o mesmo problema achei que faria sentido fazer coro ao colega @iDanielScofield)

**Comment by HenriqueSimoes82** [comment]
@iDanielScofield e @erikacarvalho 

Problema identificado e corrigido. Obrigado pelo reporte detalhado.
