### ISSUE TITLE
Parameter Id

### ISSUE THREAD

**Issue by carlosrgj** [bacen/pix-dict-api#3]
Good afternoon,

It was missing the specification of the parameter Id the endpoint.

https://github.com/bacen/pix-dict-api/blob/e2e3aa8443c13155458295a7a252964cea53d3d7/openapi/openapi.yaml#L1058

**Comment by luizlaydner** [comment]
@carlosrgj  Obrigado! [Corrigido aqui](https://github.com/bacen/pix-dict-api/commit/7747e15d0a19c8a5ae6d130ebe9dcf2779ef78ae#diff-61d421c52ac59775eb29fb236d3d6f5aR1063)
