### ISSUE TITLE
Existência de um link para o swagger

### ISSUE THREAD

**Issue by TawanReis1** [bacen/pix-dict-api#30]
Boa tarde, pessoal!

Vocês possuem algum link do swagger dessa nova versão do DICT? Antes eu pegava o openapi.yaml e colava num serviço para transformar numa documentação. Mas agora como a referência de responses e schemas estão fora do openapi.yaml, não está dando mais para fazer isso. Poderiam me ajudar com isso?

Atenciosamente,
Tawan Abreu.

**Comment by sibelius** [comment]
https://developers.openpix.com.br/dict/

ou baixar daqui https://github.com/bacen/pix-dict-api/releases/tag/1.4.0

**Comment by TawanReis1** [comment]
Muito obrigado, sibelius!
