### ISSUE TITLE
API DICT > Refund > AnalysisResult 

### ISSUE THREAD

**Issue by amandachermont** [bacen/pix-dict-api#37]
Prezados, boa tarde.

Notamos que existe um erro de ortografia na API do DICT em uma das opções do resultado da análise da devolução, sendo as opções:
- "REJECTED"
-  "TOTALLY_ACCEPTED" 
- "PARCIALlY_ACCEPTED" 

A ortografia correta seria "PARTIALLY_ACCEPTED". Poderiam por gentileza confirmar se devemos prosseguir com a escrita refletida na API para o lançamento do dia 16 ou se devemos considerar a ortografia correta?

**Comment by JulioROliveira** [comment]
E percebe-se que o GitHub do DICT do BACEN está abandonado pelos mantenedores, isso há poucos dias da obrigatoriedade de disponibilidade do recurso por parte do PSP's

**Comment by amandachermont** [comment]
@HenriqueSimoes82 @judahreis poderiam nos ajudar por favor?

**Comment by erikacarvalho** [comment]
@HenriqueSimoes82 @judahreis vai ser aceito o valor "PARCIAL**L**Y_ACCEPTED"?

**Comment by BrunoKayser** [comment]
Foi atualizado a alguns dias a documentação ajustando esse campo:  https://github.com/bacen/pix-dict-api/releases/tag/1.7.1
