### ISSUE TITLE
Massa de dados para testes

### ISSUE THREAD

**Issue by JeanFabichaki** [bacen/pix-dict-api#4]
Olá, após criar um novo Vínculo e tentar consultá-la recebo um erro informando que não posso consultar vínculos que estão sobe minha custódia. Vocês possuem uma massa de dados de teste para consultas de vínculos?

**Comment by luizlaydner** [comment]
O erro retornado ao consultar vínculo que está sob custódia do participante é esperado. No cenário de _booktransfer_ não deve ser feita consulta ao DICT.
Para teste em homologação, você pode consultar o CNPJ do Bacen: 00038166000105 .
Em breve, vamos disponibilizar um mecanismo que permitirá um participante controlar um outro participante "virtual". Isso facilitará  a realização de testes.
