### ISSUE TITLE
GetEntryResponse com domínio (type) de estatística inválido

### ISSUE THREAD

**Issue by leandrocredendio** [bacen/pix-dict-api#42]
Prezados,

Estamos recebendo no GetEntryResponse do ambiente não produtivo o atributo "type" das estatísticas com um tipo que não consta nas documentações da [API do Dict](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API-DICT-1-7-0.html).
Abaixo exemplo do XML recebido com o tipo "REJECTED".

`<GetEntryResponse>
    <CorrelationId>B202111160943372a2cc27f3bac86f0a</CorrelationId>
    <ResponseTime>2021-11-16T12:43:37.614Z</ResponseTime>
    <Entry>
        <Key>lin@itau.com</Key>
        <KeyType>EMAIL</KeyType>
        <Account>
            <Participant>60701190</Participant>
            <Branch>1500</Branch>
            <AccountNumber>00589328</AccountNumber>
            <AccountType>CACC</AccountType>
            <OpeningDate>2019-03-17T03:00:00Z</OpeningDate>
        </Account>
        <Owner>
            <Type>NATURAL_PERSON</Type>
            <TaxIdNumber>38402631827</TaxIdNumber>
            <Name>PMD Rafa Biiir</Name>
        </Owner>
        <CreationDate>2021-11-14T14:30:11.299Z</CreationDate>
        <KeyOwnershipDate>2021-11-14T14:30:11.298Z</KeyOwnershipDate>
    </Entry>
    <Statistics>
        <LastUpdated>2021-11-15T19:18:31.335Z</LastUpdated>
        <Counters>
            <Counter by=\"KEY\" d3=\"11\" d30=\"11\" m6=\"11\" type=\"SETTLEMENTS\"/>
            <Counter by=\"OWNER\" d3=\"11\" d30=\"36\" m6=\"36\" type=\"SETTLEMENTS\"/>
            <Counter by=\"ACCOUNT\" d3=\"11\" d30=\"36\" m6=\"36\" type=\"SETTLEMENTS\"/>
            <Counter by=\"KEY\" d3=\"1\" d30=\"1\" m6=\"1\" type=\"REPORTED_FRAUDS\"/>
            <Counter by=\"OWNER\" d3=\"1\" d30=\"3\" m6=\"2\" type=\"REPORTED_FRAUDS\"/>
            <Counter by=\"ACCOUNT\" d3=\"1\" d30=\"3\" m6=\"2\" type=\"REPORTED_FRAUDS\"/>
            <Counter by=\"KEY\" d3=\"0\" d30=\"0\" m6=\"0\" type=\"CONFIRMED_FRAUDS\"/>
            <Counter by=\"OWNER\" d3=\"0\" d30=\"0\" m6=\"0\" type=\"CONFIRMED_FRAUDS\"/>
            <Counter by=\"ACCOUNT\" d3=\"0\" d30=\"0\" m6=\"0\" type=\"CONFIRMED_FRAUDS\"/>
            **<Counter by=\"KEY\" d3=\"0\" d30=\"0\" m6=\"0\" type=\"REJECTED\"/>
            <Counter by=\"OWNER\" d3=\"0\" d30=\"0\" m6=\"0\" type=\"REJECTED\"/>
            <Counter by=\"ACCOUNT\" d3=\"0\" d30=\"0\" m6=\"0\" type=\"REJECTED\"/>**
        </Counters>
    </Statistics>
</GetEntryResponse>`

**Comment by leandrocredendio** [comment]
@judahreis @bcb-thiago @luizlaydner poderiam nos ajudar?

**Comment by thiagostahlschmidt** [comment]
@leandrocredendio, 

Obrigado por nos informar do problema.
A versão 1.7.1 foi disponibilizada com o novo tipo.
