### ISSUE TITLE
Infração referente bloqueio cautelar

### ISSUE THREAD

**Issue by amandachermont** [bacen/pix-dict-api#43]
Prezados, boa tarde.

Recebemos uma transferência que resultou em um bloqueio cautelar e a devolução para o PSP do pagador. Como foi confirmada a suspeita de fraude do cliente recebedor, realizamos abertura de uma infração do tipo "fraude" (infraction-report: 9d122d63-b6e5-485c-bd98-5a4fa976b3a8) como "credited_participant", porém ao tentar "agree" com essa infração, o BC está nos retornando o erro abaixo:

 <type>https://dict.pi.rsfn.net.br/api/v1/error/Forbidden</type>
  <title>Forbidden</title>
  <status>403</status>
  <detail>Participant is not allowed to access this resource</detail>

Poderiam por favor nos orientar se a infração deveria ser aberta de outra forma para possibilitar a abertura e conclusão pelo PSP recebedor neste cenário?

**Comment by amandachermont** [comment]
Foi esclarecido que, para o cenário relatado, o PSP deverá abrir a notificação informando “transactiontype = SPI” e "transactionresult = rejected_payee"

**Comment by GabrielSouzasbl** [comment]
Aqui ele só aceita este tipo de "transacitonType" e "transactionresult" se for uma transação interna. Transações entre PSPs diferentes retorna o erro: "Credited and Debited participant must be the same of the submitter".
