### ISSUE TITLE
Revisar documentação contendo Erros

### ISSUE THREAD

**Issue by morellibmv** [bacen/pix-dict-api#8]
Fizemos uma chamada para criação de um Relato de Infração e recebemos um Problem com um type não previsto na documentação

type retornado: https://dict.pi.rsfn.net.br/api/v1/error/InfractionReportTransactionNotSettled

Este type não está na documentação disponibilizada em https://github.com/bacen/pix-dict-api/blob/master/openapi/openapi.yaml e com isso não estamos conseguindo fazer os devidos tratamentos.

**Comment by luizlaydner** [comment]
Obrigado por apontar! É um erro novo que estará na release 1.0.0 da spec , a ser liberada hoje ainda.
